services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    volumes:
      - ./data:/opt/bitnami/spark/data:rw
      - ./scripts:/opt/bitnami/spark/scripts:rw
    environment:
      - SPARK_MODE=master
      - SPARK_EXECUTOR_INSTANCES=4 # worker nya cuy
      - SPARK_EXECUTOR_MEMORY=4g
      - SPARK_EXECUTOR_CORES=2
      - SPARK_SUBMIT_OPTIONS=--conf spark.executor.instances=2 --executor-memory 4G --executor-cores 2
    ports:
      - "8080:8080"
      - "7077:7077"
  
  spark-worker:
    image: bitnami/spark:latest
    deploy:
      replicas: 4 # jumlah worker
    volumes:
      - ./data:/opt/bitnami/spark/data:rw
      - ./scripts:/opt/bitnami/spark/scripts:rw
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
    depends_on:
      - spark-master
